[2023-12-13T23:20:58.112+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.create_domains_table scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-13T23:20:58.115+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.create_domains_table scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-13T23:20:58.115+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-13T23:20:58.120+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_domains_table> on 2023-12-12 00:00:00+00:00
[2023-12-13T23:20:58.124+0000] {standard_task_runner.py:57} INFO - Started process 103 to run task
[2023-12-13T23:20:58.127+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'create_domains_table', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0lt8nn5k']
[2023-12-13T23:20:58.130+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask create_domains_table
[2023-12-13T23:20:58.153+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.create_domains_table scheduled__2023-12-12T00:00:00+00:00 [running]> on host dde03b621bd8
[2023-12-13T23:20:58.184+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='create_domains_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2023-12-13T23:20:58.185+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS DomainsToScrape (
            id  SERIAL PRIMARY KEY,
            domain VARCHAR(128) UNIQUE,
            scrapped BOOlEAN
        );
        
[2023-12-13T23:20:58.192+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_homework_2` isn't defined
[2023-12-13T23:20:58.194+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag, task_id=create_domains_table, execution_date=20231212T000000, start_date=20231213T232058, end_date=20231213T232058
[2023-12-13T23:20:58.200+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task create_domains_table (The conn_id `postgres_homework_2` isn't defined; 103)
[2023-12-13T23:20:58.219+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T23:20:58.231+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
